from typing import TypedDict, Annotated, Dict, Any, List
import operator

class AgentState(TypedDict):
    """
    The global state passed through the LangGraph orchestrator.
    It holds the ticker, contextual data, and accumulates reports 
    from each agent as it passes through the nodes.
    """
    ticker: str
    analysis_date: str
    
    # Context injected by the Data Loaders / Screener
    market_metrics: Dict[str, Any]
    macro_context: Dict[str, Any]
    research_scorecard: Dict[str, Any]
    execution_plan: Dict[str, Any]
    risk_plan: Dict[str, Any]
    
    # Reports generated by Tier 1 Analysts (Fundamental, Technical, etc.)
    # We use operator.ior to merge dictionaries as different analysts add their reports
    analyst_reports: Annotated[Dict[str, Any], operator.ior]
    
    # The output of the Bull/Bear debate, merged from parallel nodes
    debate_transcript: Annotated[Dict[str, Any], operator.ior]
    debate_round: int
    
    # The actionable plan proposed by the Trader Agent
    trader_plan: Dict[str, Any]
    
    # The Risk Manager's evaluation
    risk_assessment: Dict[str, Any]
    
    # The final decision and reasoning by the Portfolio Manager
    final_decision: str
    confidence: float
    pm_reasoning: str
    
    # Audit trail
    audit_status: str
    audit_notes: List[str]
